manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar #rgb widget for xiao seeed
      url-base: https://github.com/caksoylar
    # support nice_oled and nice_epaper
  #    - name: mctechnology17
  #      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      #revision: main
      revision: v0.3.0 #pin to 0.3 for now
      import: app/west.yml
    - name: zmk-rgbled-widget #rgb widget for xiao seeed
      remote: caksoylar
      revision: main
    # support nice_oled and nice_epaper
  #    - name: zmk-nice-oled
  #      remote: mctechnology17
  #      revision: main
  self:
    path: config
